#
# Copyright (C) 2017 by Author: Aroudj, Samir, born in Suhl, Thueringen, Germany
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the BSD 3-Clause license. See the License.txt file for details.
#

# common things for file generation using CMAKE

set(FILE_GENERATION_INPUT_DIR ${BASE_PROJECT_DIR}/CMake/FileGeneration)
set(FILE_GENERATION_OUTPUT_DIR ${BASE_BUILD_OUTPUT_DIR}/GeneratedFiles)

file(MAKE_DIRECTORY ${FILE_GENERATION_OUTPUT_DIR})

include_directories(${FILE_GENERATION_INPUT_DIR})
include_directories(${FILE_GENERATION_OUTPUT_DIR})

# use this to gather source files generated by CMAKE
set(generatedHeaderFiles "")
set(generatedSourceFiles "")