find_path(TINYXML2_INCLUDE_DIR NAMES tinyxml2.h)
find_library(TINYXML2_LIBRARY_DEFAULT NAMES tinyxml2)

set(TINYXML2_LIBRARY_RELEASE "${TINYXML2_LIBRARY_DEFAULT}" CACHE FILEPATH "Path to tinyxml2 release library.")
set(TINYXML2_LIBRARY_DEBUG "${TINYXML2_LIBRARY_DEFAULT}" CACHE FILEPATH "Path to tinxml2 debug library.")
set(TINYXML2_LIBRARIES "debug ${TINYXML2_LIBRARY_DEBUG}")
set(TINYXML2_LIBRARIES ${TINYXML2_LIBRARIES} "optimized ${TINYXML2_LIBRARY_RELEASE}")

mark_as_advanced(TINYXML2_INCLUDE_DIR TINYXML2_LIBRARY_DEBUG TINYXML2_LIBRARY_DEFAULT TINYXML2_LIBRARY_RELEASE)


include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(TINYXML2 DEFAULT_MSG TINYXML2_LIBRARIES TINYXML2_INCLUDE_DIR)
